# Generated by Django 4.1.3 on 2024-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0009_alter_position_usd_value_of_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
