# Generated by Django 4.2.11 on 2026-04-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0009_alter_position_usd_value_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=7000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='position',
            name='USD_value_of_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Purchase Value'),
        ),
    ]
